// Auto-generated by scripts/generate-covers.js — do not edit.
// Add images to assets/covers/ (e.g. party_4.png) and they will appear in the cover picker.

export const COVER_SOURCES: Record<string, number> = {
  "birthday_1": require("../../assets/covers/birthday_1.png"),
  "birthday_2": require("../../assets/covers/birthday_2.png"),
  "birthday_3": require("../../assets/covers/birthday_3.png"),
  "birthday_4": require("../../assets/covers/birthday_4.png"),
  "birthday_5": require("../../assets/covers/birthday_5.png"),
  "dad": require("../../assets/covers/dad.png"),
  "ghabga_1": require("../../assets/covers/ghabga_1.png"),
  "graduation_1": require("../../assets/covers/graduation_1.png"),
  "graduation_2": require("../../assets/covers/graduation_2.png"),
  "graduation_3": require("../../assets/covers/graduation_3.png"),
  "graduation_4": require("../../assets/covers/graduation_4.png"),
  "graduation_5": require("../../assets/covers/graduation_5.png"),
  "istiraha_1": require("../../assets/covers/istiraha_1.png"),
  "majlis_1": require("../../assets/covers/majlis_1.png"),
  "party_1": require("../../assets/covers/party_1.png"),
  "party_2": require("../../assets/covers/party_2.png"),
  "party_3": require("../../assets/covers/party_3.png"),
  "pizzz_night_1": require("../../assets/covers/pizzz_night_1.jpg"),
  "pizzz_night_2": require("../../assets/covers/pizzz_night_2.jpg"),
  "ramadan_1": require("../../assets/covers/ramadan_1.png"),
  "ramadan_2": require("../../assets/covers/ramadan_2.png"),
  "wedding_1": require("../../assets/covers/wedding_1.png"),
};
