/**
 * Scans assets/covers/ and generates src/utils/covers.generated.ts
 * so any new image (e.g. graduation_2.png, party_4.png) shows in the cover picker.
 * - Runs automatically before "npm start" (prestart).
 * - After adding images while dev is running: run "npm run generate-covers" or
 *   "node scripts/watch-covers.js" in another terminal to auto-regenerate on change.
 */
const fs = require("fs");
const path = require("path");

const COVERS_DIR = path.join(__dirname, "..", "assets", "covers");
const OUT_FILE = path.join(__dirname, "..", "src", "utils", "covers.generated.ts");

const IMAGE_EXT = /\.(png|jpg|jpeg|webp)$/i;

if (!fs.existsSync(COVERS_DIR)) {
  fs.writeFileSync(
    OUT_FILE,
    "// Auto-generated. Run: node scripts/generate-covers.js\n// No assets/covers folder found.\nexport const COVER_SOURCES: Record<string, number> = {};\n"
  );
  process.exit(0);
}

const files = fs.readdirSync(COVERS_DIR).filter((f) => IMAGE_EXT.test(f));
const entries = files
  .map((f) => {
    const key = path.basename(f, path.extname(f));
    const relPath = path.relative(path.dirname(OUT_FILE), path.join(COVERS_DIR, f)).replace(/\\/g, "/");
    return `  "${key}": require("${relPath}"),`;
  })
  .sort((a, b) => a.localeCompare(b));

const content = `// Auto-generated by scripts/generate-covers.js — do not edit.
// Add images to assets/covers/ (e.g. party_4.png) and they will appear in the cover picker.

export const COVER_SOURCES: Record<string, number> = {
${entries.join("\n")}
};
`;

fs.writeFileSync(OUT_FILE, content);
console.log("generate-covers: wrote", entries.length, "covers to src/utils/covers.generated.ts");
